# Generated by Django 3.1 on 2020-11-06 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='workshops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='kala', max_length=30)),
                ('organizer', models.CharField(default='WCE', max_length=30)),
                ('location', models.CharField(default='Sangli', max_length=50)),
                ('mode', models.BooleanField()),
                ('startdate', models.DateTimeField(auto_now_add=True)),
                ('enddate', models.DateTimeField(auto_now_add=True)),
                ('certification', models.URLField()),
                ('certBool', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
        migrations.CreateModel(
            name='webinars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='kala', max_length=30)),
                ('organizer', models.CharField(default='WCE', max_length=30)),
                ('location', models.CharField(default='Sangli', max_length=50)),
                ('mode', models.BooleanField()),
                ('startdate', models.DateTimeField(auto_now_add=True)),
                ('enddate', models.DateTimeField(auto_now_add=True)),
                ('certification', models.URLField()),
                ('certBool', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
        migrations.CreateModel(
            name='courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='C++', max_length=30)),
                ('domain', models.CharField(default='CSE', max_length=30)),
                ('platform', models.CharField(default='Udemy', max_length=30)),
                ('startDate', models.DateTimeField(auto_now_add=True)),
                ('endDate', models.DateTimeField(auto_now_add=True)),
                ('certification', models.URLField()),
                ('certBool', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
