# Generated by Django 3.1.1 on 2020-11-19 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0005_auto_20201117_1035'),
    ]

    operations = [
        migrations.CreateModel(
            name='competitions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compname', models.CharField(max_length=50)),
                ('organizer', models.CharField(default='Walchand College of Engineering, Sangli', max_length=60)),
                ('location', models.CharField(default='ONLINE', max_length=15)),
                ('mode', models.CharField(max_length=15)),
                ('projectTitle', models.CharField(default='No Title', max_length=45)),
                ('description', models.TextField(default='No description')),
                ('startdate', models.DateTimeField(auto_now_add=True)),
                ('enddate', models.DateTimeField(auto_now_add=True)),
                ('winner', models.BooleanField()),
                ('certBool', models.BooleanField()),
                ('certification', models.URLField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='teamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comps', models.ManyToManyField(to='student.competitions')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
