# Generated by Django 3.1.1 on 2020-11-19 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0006_competitions_teammember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitions',
            name='compname',
            field=models.CharField(default='WCE Hackathon', max_length=50),
        ),
        migrations.AlterField(
            model_name='competitions',
            name='location',
            field=models.CharField(default='Sangli', max_length=15),
        ),
        migrations.AlterField(
            model_name='competitions',
            name='mode',
            field=models.CharField(default='Online', max_length=15),
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='comps',
        ),
        migrations.AddField(
            model_name='teammember',
            name='comps',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.competitions'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
