# Generated by Django 3.1.1 on 2020-11-20 10:41

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0007_auto_20201119_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webinars',
            name='enddate',
        ),
        migrations.RemoveField(
            model_name='webinars',
            name='startdate',
        ),
        migrations.AddField(
            model_name='webinars',
            name='endDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='webinars',
            name='startDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='competitions',
            name='enddate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='competitions',
            name='mode',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='competitions',
            name='startdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='courses',
            name='endDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='courses',
            name='startDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='workshops',
            name='enddate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='workshops',
            name='startdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='paperpublications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papertitle', models.CharField(default='Research Paper', max_length=60)),
                ('mode', models.BooleanField()),
                ('confname', models.CharField(default='No Title', max_length=55)),
                ('startdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('enddate', models.DateTimeField(default=django.utils.timezone.now)),
                ('location', models.CharField(default='Sangli', max_length=40)),
                ('level', models.BooleanField()),
                ('publicationPorR', models.BooleanField()),
                ('publicationtype', models.CharField(default='Book Chapter', max_length=20)),
                ('volumenumber', models.IntegerField()),
                ('issuenumber', models.IntegerField()),
                ('isbnissndoi', models.CharField(default='ISBN', max_length=10)),
                ('pagefrom', models.IntegerField()),
                ('pageto', models.IntegerField()),
                ('month', models.CharField(default='September', max_length=15)),
                ('year', models.IntegerField(default=2020, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='year')),
                ('paperurl', models.URLField(default='http://www.sciencedirect.com/science/article/pii/S0747563216304411')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papers', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.paperpublications')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
