# Generated by Django 3.1 on 2020-11-29 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_auto_20201120_1041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competitions',
            old_name='enddate',
            new_name='endDate',
        ),
        migrations.RenameField(
            model_name='competitions',
            old_name='startdate',
            new_name='startDate',
        ),
        migrations.RenameField(
            model_name='paperpublications',
            old_name='enddate',
            new_name='endDate',
        ),
        migrations.RenameField(
            model_name='paperpublications',
            old_name='startdate',
            new_name='startDate',
        ),
        migrations.RenameField(
            model_name='workshops',
            old_name='enddate',
            new_name='endDate',
        ),
        migrations.RenameField(
            model_name='workshops',
            old_name='startdate',
            new_name='startDate',
        ),
        migrations.AlterField(
            model_name='competitions',
            name='certBool',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='paperpublications',
            name='confname',
            field=models.CharField(default='No Title', max_length=100),
        ),
        migrations.AlterField(
            model_name='paperpublications',
            name='isbnissndoi',
            field=models.CharField(default='ISBN', max_length=20),
        ),
        migrations.AlterField(
            model_name='paperpublications',
            name='location',
            field=models.CharField(default='Sangli', max_length=100),
        ),
        migrations.AlterField(
            model_name='paperpublications',
            name='papertitle',
            field=models.CharField(default='Research Paper', max_length=100),
        ),
        migrations.AlterField(
            model_name='paperpublications',
            name='publicationtype',
            field=models.CharField(default='Book Chapter', max_length=100),
        ),
    ]
