# Generated by Django 3.1.1 on 2020-11-30 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='conclusion',
            field=models.CharField(default='NA', max_length=30000),
        ),
    ]
